// File: ./ex-target/Rectifier.v
// Generated by MyHDL 1.0dev
// Date: Mon Oct  5 14:11:09 2015


`timescale 1ns/10ps

module Rectifier (
    y,
    y_dx,
    x
);
// Rectified linear unit (ReLU) and derivative model using fixbv type.
// 
// :param y: return max(0, x) as fixbv
// :param y_dx: return d/dx max(0, x) as fixbv
// :param x: input value as fixbv
// :param leaky_val: factor for leaky ReLU, 0.0 without
// :param fix_min: fixbv min value
// :param fix_max: fixbv max value
// :param fix_res: fixbv resolution

output signed [15:0] y;
reg signed [15:0] y;
output signed [15:0] y_dx;
reg signed [15:0] y_dx;
input signed [15:0] x;






always @(x) begin: RECTIFIER_RELU
    reg signed [16-1:0] zero;
    reg signed [16-1:0] leaky;
    if ((x > zero)) begin
        y = x;
    end
    else begin
        y = fixbv((leaky * x));
    end
end


always @(x) begin: RECTIFIER_RELU_DX
    reg signed [16-1:0] zero;
    reg signed [16-1:0] leaky;
    reg signed [16-1:0] one;
    if ((x > zero)) begin
        y_dx = one;
    end
    else begin
        y_dx = leaky;
    end
end

endmodule
